
<div class="footer-container">
    <div class="footer">
        
    </div>
</div>

<div id="footer">
		<div class="footer5 footer11">
			<div class="container">
				<div class="footer-top footer-top5">
					<div class="logo-footer">
						<a href="#"><img alt="" src="http://localhost/magento/skin/frontend/mypackage/default/images/lets-shop.png"></a>
					</div>
					<div class="menu-footer">
						<ul>
							
							<li><a href="http://localhost/magento/index.php/sales/order/history/">My Orders </a></li> |
							<li><a href="http://localhost/magento/index.php/customer-service/">Customer Service</a></li> |
							<li><a href="http://localhost/magento/index.php/about-magento-demo-store/">About </a></li>
							
						</ul>
					</div>
				</div>
				<!-- End Footer top -->
				
				<div class="list-footer-box5">
					<div class="row">
						<div class="col-md-3 col-sm-6 col-xs-12">
							<div class="footer-box">
								<h2>My Account</h2>
								<ul class="footer-menu-box">
									<li><a href="http://localhost/magento/index.php/sales/order/history/">My orders</a></li>
									<li><a href="http://localhost/magento/index.php/customer/address/new/">My addresses</a></li>
									<li><a href="http://localhost/magento/index.php/customer/account/edit/">My personal info</a></li>
								</ul>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-12">
							<div class="footer-box">
								<h2>Help</h2>
								<ul class="footer-menu-box">
									
									<li><a href="http://localhost/magento/index.php/contacts/index">Contact us</a></li>
									<li><a href="http://localhost/magento/sitemap.xml">Site Map</a></li>
									<li><a href="http://localhost/magento/index.php/customer-service/">Delivery &amp; returns</a></li>
								</ul>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-12">
							<div class="footer-box">
								<h2>Further information</h2>
								<ul class="footer-menu-box">
									
									<li><a href="http://localhost/magento/index.php/about-magento-demo-store/">About us</a></li>
									<li><a href="http://localhost/magento/index.php/privacy-policy-cookie-restriction-mode/">Privacy</a></li>
									<li><a href="#">Terms &amp; conditions</a></li>
								</ul>
							</div>
						</div>
						<div class="col-md-3 col-sm-6 col-xs-12">
							<div class="footer-box">
								<h2>Contact Us</h2>
								<ul class="footer-box-contact">
									<li><i class="fa fa-home"></i> Our business address is </li>
									<li><i class="fa fa-mobile"></i> + 020.566.8866</li>
									<li><i class="fa fa-envelope"></i> <a href="mailto:support@letsshop.com">support@letsshop.com</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<!-- End List Box -->
				<div class="footer-bottom5">
					<div class="row">
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="copyright">
								<address class="copyright"><?php echo $this->getCopyright() ?></address>
							</div>
						</div>
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="payment2 payment-method">
								<a href="#"><img alt="" src="http://localhost/magento/skin/frontend/mypackage/default/images/pay1.png"></a>
								<a href="#"><img alt="" src="http://localhost/magento/skin/frontend/mypackage/default/images/pay3.png"></a>
								<a href="#"><img alt="" src="http://localhost/magento/skin/frontend/mypackage/default/images/pay4.png"></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
